name: Deploy Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install Workload
        run: dotnet workload install maui

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Docs
        run: |
          $repos = @(
            @{ Url = "https://github.com/qian-o/Zenith.NET"; Branch = "master"; DocsFolder = "documents"; OutputFolder = "Zenith.NET" }
          )

          foreach ($repo in $repos) {
            Write-Host "Building $($repo.OutputFolder) docs..."
            git clone -b $repo.Branch $repo.Url source-repo
            $env:DOCFX_SOURCE_BRANCH_NAME = $repo.Branch
            docfx source-repo/$($repo.DocsFolder)/docfx.json
            Remove-Item -Recurse -Force $repo.OutputFolder -ErrorAction SilentlyContinue
            Copy-Item -Recurse "source-repo/$($repo.DocsFolder)/_site" $repo.OutputFolder
            Remove-Item -Recurse -Force "source-repo"
          }

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-docs
          commit-message: "Update documentation"
          title: "Update documentation"
          body: "This PR updates the documentation."
          labels: "documentation"
